PREFIX mat: <http://bimerr.iot.linkeddata.es/def/material-properties#>
PREFIX mmo: <https://w3id.org/pmd/materials-mechanics-ontology/>
PREFIX saref: <https://w3id.org/saref#>
PREFIX bso: <https://w3id.org/bso#>
PREFIX cpo: <https://w3id.org/cpo#>
PREFIX inst: <https://random-url-to-your-data.com/data#>

DELETE {
    ?CCTE saref:hasValue ?oldCCTEv .
}
INSERT {
    ?CCTE a mmo:ThermalExpansionCoefficient .
    ?CCTE saref:hasValue ?CTEv .
    ?C bso:hasMaterialProperty ?CCTE .
}
WHERE {
    ?CTE a mmo:ThermalExpansionCoefficient .
    
    ?C cpo:isMadeOfComponentMaterial ?CA .
    ?CA bso:hasMaterialProperty ?CTE .
    ?CTE saref:hasValue ?CTEv .
    
    BIND (IRI(CONCAT(STR(?C), "-ThermalExpansionCoefficient")) AS ?CCTE) .
    
    OPTIONAL{
        ?C bso:hasMaterialProperty ?CCTE .
        ?CCTE a mmo:ThermalExpansionCoefficient .
    }
    
    OPTIONAL{
        ?C bso:hasMaterialProperty ?CCTE .
        ?CCTE a mmo:ThermalExpansionCoefficient .
        ?CCTE saref:hasValue ?oldCCTEv.
    }
}